server:
  port: 7900
spring:
  application:
    name: mall-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/as26220635/mall.git
          username: 851758629@qq.com
          password: qw26220635..
          search-paths: config-file
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.75.128}
    port: ${RABBITMQ_PORT:5672}
    username: admin
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://admin:123456@192.168.75.128:8000/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS