server:
  port: 7900
spring:
  application:
    name: mall-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/as26220635/mall.git
          username: 851758629@qq.com
          password: qw26220635..
          search-paths: config-file
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8000/eureka/