server:
  port: 8000
spring:
  application:
    name: mall-server-eureka
  security:
    user:
      name: root
      password: 123456
eureka:
  instance:
    hostname: localhost
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

