server:
  port: 8010
spring:
  application:
    name: mall-service-user-provider
  zipkin:
    #配置zipkin发送类型为kafka
    sender:
      type: kafka
    kafka:
      topic: zipkin
  kafka:
    bootstrap-servers: 192.168.75.128:9092
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 192.168.75.128
    port: 5672
    username: admin
    password: 123456
zipkin:
  rabbitmq:
    queue: zipkin
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.75.128:8000/eureka/