server:
  port: 8010
spring:
  application:
    name: mall-service-user-provider
  zipkin:
    base-url: http://192.168.75.128:7700
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.75.128:8000/eureka/