server:
  port: 8015
spring:
  application:
    name: mall-service-user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.75.128:8000/eureka/
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true