server:
  port: 8015
spring:
  application:
    name: mall-service-user-consumer
  zipkin:
    #配置zipkin发送类型为kafka
    sender:
      type: kafka
    kafka:
      topic: zipkin
  kafka:
    producer:
      bootstrap-servers: 192.168.75.128:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 192.168.75.128
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.75.128:8000/eureka/
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#ribbon的超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
