server:
  port: 8015
spring:
  application:
    name: mall-service-user-consumer
  zipkin:
    base-url: http://192.168.75.128:7700
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.75.128:8000/eureka/
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#ribbon的超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
